"""
This type stub file was generated by pyright.
"""

import torch
from torchopt._src.base import GradientTransformation

def zero_nan_hook(g: torch.Tensor) -> torch.Tensor:
    """Registers a zero nan hook to replace nan with zero."""
    ...

def register_hook(hook) -> GradientTransformation:
    """Stateless identity transformation that leaves input gradients untouched.

    This function passes through the *gradient updates* unchanged.

    Returns:
        An ``(init_fn, update_fn)`` tuple.
    """
    ...

