"""
This type stub file was generated by pyright.
"""

import torch
from typing import Iterable
from torchopt._src.optimizer.base import Optimizer
from torchopt._src.typing import ScalarOrSchedule

class SGD(Optimizer):
    """The classic SGD optimizer.

    See Also:
        - The functional SGD optimizer: :func:`torchopt.sgd`.
        - The differentiable meta-SGD optimizer: :class:`torchopt.MetaSGD`.
    """
    def __init__(self, params: Iterable[torch.Tensor], lr: ScalarOrSchedule, momentum: float = ..., weight_decay: float = ..., dampening: float = ..., nesterov: bool = ..., maximize: bool = ...) -> None:
        r"""The :meth:`init` function.

        Args:
            params: (iterable of torch.Tensor)
                An iterable of :class:`torch.Tensor`\s. Specifies what tensors should be optimized.
            lr: This is a fixed global scaling factor.
            momentum: (default: :const:`0.0`)
                The decay rate used by the momentum term. The momentum is not used when it is set to
                :const:`0.0`.
            weight_decay: (default: :const:`0.0`)
                Weight decay, add L2 penalty to parameters.
            dampening: (default: :const:`0.0`)
                Dampening for momentum.
            nesterov: (default: :data:`False`)
                Whether to use Nesterov momentum.
            maximize: (default: :data:`False`)
                Maximize the params based on the objective, instead of minimizing.
        """
        ...
    


