"""
This type stub file was generated by pyright.
"""

from torchopt._src import accelerated_op_available, clip, combine, hook, implicit_diff, linear_solve, schedule, visual
from torchopt._src.alias import adam, adamw, rmsprop, sgd
from torchopt._src.clip import clip_grad_norm
from torchopt._src.combine import chain
from torchopt._src.optimizer import Adam, AdamW, Optimizer, RMSProp, RMSprop, SGD, meta
from torchopt._src.optimizer.func import FuncOptimizer
from torchopt._src.optimizer.meta import MetaAdam, MetaAdamW, MetaOptimizer, MetaRMSProp, MetaRMSprop, MetaSGD
from torchopt._src.update import apply_updates
from torchopt._src.utils import extract_state_dict, pytree, recover_state_dict, stop_gradient
from torchopt.version import __version__

"""TorchOpt: a high-performance optimizer library built upon PyTorch."""
__all__ = ['accelerated_op_available', 'clip', 'combine', 'hook', 'schedule', 'visual', 'implicit_diff', 'linear_solve', 'adam', 'adamw', 'rmsprop', 'sgd', 'clip_grad_norm', 'chain', 'Optimizer', 'SGD', 'Adam', 'AdamW', 'RMSProp', 'RMSprop', 'MetaOptimizer', 'MetaSGD', 'MetaAdam', 'MetaAdamW', 'MetaRMSProp', 'MetaRMSprop', 'FuncOptimizer', 'apply_updates', 'extract_state_dict', 'recover_state_dict', 'stop_gradient']
