"""
This type stub file was generated by pyright.
"""

from torchopt._src.optimizer.meta.adam import MetaAdam
from torchopt._src.optimizer.meta.adamw import MetaAdamW
from torchopt._src.optimizer.meta.base import MetaOptimizer
from torchopt._src.optimizer.meta.rmsprop import MetaRMSProp, MetaRMSprop
from torchopt._src.optimizer.meta.sgd import MetaSGD

